import "./globals.scss";
import "react-toastify/dist/ReactToastify.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cookies } from "next/headers";

import { HeaderContainer } from "components/Header";
import { ToastContainer } from "react-toastify";
import { EGlobalTheme, THEME_COOKIE } from "lib/constants";
import { SidebarContainer } from "components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const theme =
    (cookies().get(THEME_COOKIE)?.value as EGlobalTheme) || EGlobalTheme.LIGHT;

  return (
    <html lang="en" className={`${theme === EGlobalTheme.DARK ? "dark" : ""}`}>
      <body
        className={inter.className + " h-full bg-gray-100 dark:bg-slate-900"}
      >
        <ToastContainer position="bottom-left" />
        <div className="flex">
          <SidebarContainer />
          <div className="w-full">
            <HeaderContainer theme={theme} />

            <div id="contentWidth" className={`ml-auto`}>
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
