import "./globals.scss";
import "react-toastify/dist/ReactToastify.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cookies } from "next/headers";

import Header from "components/Header";
import { ToastContainer } from "react-toastify";
import { EGlobalTheme, THEME_COOKIE } from "lib/constants";
import Sidebar from "components/Sidebar";
import QueryProvider from "components/providers/QueryProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const theme =
    (cookies().get(THEME_COOKIE)?.value as EGlobalTheme) || EGlobalTheme.LIGHT;

  return (
    <html lang="en" className={`${theme === EGlobalTheme.DARK ? "dark" : ""}`}>
      <body
        className={inter.className + " h-full bg-gray-100 dark:bg-slate-900"}
      >
        <QueryProvider>
          <ToastContainer position="bottom-left" />
          <div className="flex">
            <Sidebar />
            <div className="w-full">
              <Header theme={theme} />

              <div className="ml-auto max-w-[85rem] px-4 py-10 sm:px-6 lg:px-8 lg:py-14 mx-auto">
                {children}
              </div>
            </div>
          </div>
        </QueryProvider>
      </body>
    </html>
  );
}
