name: Linting, testing, building
on:
  push:
    branches: [master, develop, addStorybookTests]
  pull_request:
    branches: [master, develop]
jobs:
  pipline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]

    steps:
      - uses: actions/checkout@v1
      - name: Setup Node.js environment
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.4.0

      - name: Build production project
        run: pnpm build
        if: always()

      - name: Lint
        run: pnpm lint
        if: always()

      - name: Storybook visual tests
        run: pnpm chromatic
        if: always()
