name: Linting, testing, building
on:
  push:
    branches: [master, develop, addStorybookTests]
  pull_request:
    branches: [master, develop]
jobs:
  pipline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]

    steps:
      - uses: actions/checkout@v1
      - name: Setup Node.js environment
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install node_modules
        run: npm install

      - name: Build production project
        run: npm run build
        if: always()

      - name: Lint
        run: npm run lint
        if: always()

      - name: Storybook build
        run: npm run build-storybook
        if: always()

      - name: Storybook test runner
        run: npm run test-storybook
        if: always()

      - name: Storybook visual tests
        run: npm run chromatic
        if: always()
